### PR TITLE
Issue165

### PR DESCRIPTION
**Pull request by FrauDeborah**
After chasing many rabbit trails (and learning much), simplicity reigned! In html area of displayQuestion.jsp file, added <br/> after the divCreatedBy division to force next <div> onto a new line. Verified using Foxfire, Chrome and IE.

### CODE REVIEW

**Comment by haxwell** [comment]
Hello Deborah! Thanks for this pull request.. Some advice.. Your pull request should have only the changes you made in it. If when you look at your request, you see many more commits, and files changed, than it took you to do your work, then you can be sure something is amiss. I think in this case, a large part of it is that you submitted this request directed at `haxwell\master`, instead of `haxwell\dev`. 

Try editing, or if that fails, recreating, this pull request so that it refers to the correct destination. You should only have 1 commit, and 1 file changed, in your pull request.

**Comment by FrauDeborah** [comment]
Hi Johnathan,

I’m confused as to how multiple files changed because I deleted all files off my hard drive and basically started over... 

I deleted all files in my local and in eclipse.  I did not refork because I had not pushed anything after I re-forked the other day after we talked.

I re- cloned
Set upstream to haxwell/master
I did try to sync but was told all was up to dated
created new root.war.
Then carefully applied the one change in eclipse.

I’m wondering how multiple files changed.

Oh well, I will delete everything again and start with a new fork. 

Maybe I was on your master when I made the pull request. Perhaps that is why it went to haxwell/master. This time I’ll verify I’m on FrauDeborah/issue615 in github before doing the pull request.


Regardless as to whatever happened hopefully only the one change will occur this round.


Sorry for my error.

Also to create my local dev branch this is what I’ve been doing from my local quizki directory.

git fetch upstream
git checkout -b dev upstream/dev
git branch issue165
git checkout issue165

Perhaps I should be doing this instead

git fetch origin
git checkout -b dev origin/dev
git branch issue165
git checkout issue165

I see I didn’t push issue165 correctly. My notes said to 

git push -u origin newbranch 

So I should have done

git push -u origin issue165

I just used

git push

It seamed to work. 

I’ll try again this evening.

Thank you for the feedback

Regards,

Deborah 


On Apr 3, 2018, at 1:05 PM, Johnathan James <notifications@github.com> wrote:

Hello Deborah! Thanks for this pull request.. Some advice.. Your pull request should have only the changes you made in it. If when you look at your request, you see many more commits, and files changed, than it took you to do your work, then you can be sure something is amiss. I think in this case, a large part of it is that you submitted this request directed at haxwell\master, instead of haxwell\dev.

Try editing, or if that fails, recreating, this pull request so that it refers to the correct destination. You should only have 1 commit, and 1 file changed, in your pull request.

**Comment by haxwell** [comment]
So, you created a Dev branch, and by all appearances, accurately.

Now remember, that Dev branch is farther ahead (has more changes) than our Master branch. Dev has changes that we have not yet put into Master.

So, you create a branch off of Dev (a feature branch, in the lingo) called ISSUE165. You do your work, and commit there.

So, to recap, you have Master, and then Dev which goes a little bit farther, and ISSUE165 which extends Dev, and goes even further.

So, if an asterisk represents a change.. then you can imagine the history of your repo as a series of *'s
```
Haxwell\Master [start] * * * [end]
FrauDeborah\Dev [starts where Haxwell\Master ends] * * * * * * * * * * * [end]
FrauDeborah\ISSUE165 [starts where FrauDeborah\Dev ends] * [end]
```

So, in this example, Haxwell\Master has three changes. Then you create a Dev branch in your repo. You merge in changes from the rest of the team, so your Dev has 11 more changes than Haxwell\Master (because changes are not yet being merged into Haxwell\Master. They're still in Dev branch) When you make your change in ISSUE165, and then say apply ISSUE165 to Haxwell\Master, its not just the change you made for ISSUE165, but all the changes that came from the end of Master to your current ISSUE165 branch. Those changes are necessary for me to bring Master in line with ISSUE165.

If instead, you directed the PR at my Haxwell\Dev branch, there would be many fewer changes necessary to bring Haxwell\Dev in line. In fact, the only change would be the single change you made in ISSUE165.

The long and the short of it is that you directed your pull request to Haxwell\Master, when you should have directed it to Haxwell\Dev. You can edit an existing pull request to change this, or you can just create a new one. Your choice.

**Comment by haxwell** [comment]
I typed a long time trying to figure the right way to word that.. Not sure I accomplished my goal. if the explanation of "why you are seeing extra files in your PR" doesn't make sense, let me know.

**Comment by FrauDeborah** [comment]
Thank you Johnathan.

I’ll try again in the morning when I’m thinking fresh. Rough day🤪today!

I’ll keep my fingers crossed. 

Your continued support is much appreciated. I’m not normally so slow learning new tools. 

Regards,

Deborah 


On Apr 3, 2018, at 4:17 PM, Johnathan James <notifications@github.com> wrote:

I typed a long time trying to figure the right way to word that.. Not sure I accomplished my goal. if the explanation of "why you are seeing extra files in your PR" doesn't make sense, let me know.

**Comment by haxwell** [comment]
No worries.. Git is not the simplest tool. :)

Closing in favor of #221

**Pull request closed without merging**
