### PR TITLE
objectAid class diagram generator test

### PR DESCRIPTION
**Pull request by jdisser**
I installed the ObjectAid plugin and generated a class diagram for the entities with simple drag and drop from the Navigator onto the diagram. I think the diagram is helpful for seeing the dependencies and an easy to follow reference for each class.  I put the new diagram in the Doc folder, it's the only change to the repo. From the objectAid doc the diagram will automatically change when changes are made to the code. You can zoom out to 25% and get a good overview of all the dependencies.

Wish I had something like this on that other job I mentioned!

### CODE REVIEW

**Comment by haxwell** [comment]
Hi Jim.. Sorry for the delay, finally took a look at ObjectAid.. I agree, something like this could be useful. I have two reservations.. First, its not open source. Second, its specific to Eclipse. Perhaps you could add a section in the DEVELOPER file, `Useful Tools` or the like.. and then describe this tool there. Whaddaya think?

**Comment by jdisser** [comment]
The best solution would be independent of the IDE. I think intellij has the ability to create diagrams built in(!) see here
[https://www.jetbrains.com/help/idea/working-with-diagrams.html#d878201e21](url)
It looks like Netbeans also supports UML diagrams with a tool called the modelling pack
[http://wiki.netbeans.org/NetbeansUML](url)
and here just for a (in)sanity check is what I turned up seeking the holy grail, something that runs in all three
[https://www.visual-paradigm.com/features/code-engineering-tools/](url)
now for only $99  :-(  ... they do have a $6/mo subscription but this is not exactly the grail. Definitely not open source.
There does not appear to be an easy way to store the diagram in a standard format. XMI should work that way but it's not really supported by the IDE plugins that handle the diagrams. So the only "U"niversal answer is the commercial $6/mo Visual-paradigm route (which actually does a lot more cool stuff than diagrams). It would generate XMI files but the other tools don't import them so it will not work even as a work around.
I guess the next best thing would be to document how to generate diagrams in each IDE and not include the diagrams in git. I would be happy to write the `Useful Tools` doc for Eclipse/ObjectAid and leave the other IDE's for the team.

**Comment by haxwell** [comment]
Just to clear up my "Pull Request To-Do List", I'm going to close this PR.. It will still be available in history if you want to reference it or add to it later.

**Comment by jdisser** [comment]
I have not found a really good solution for this that would work on all the different platforms for free. I was thinking about that question Brian asked during the planning meeting about a starting point to learn the codebase. A class diagram like this might work. I found I gained a much better understanding of the app by studying the Entities. The tool you talked about for displaying the schema is probably the closest thing to a universal tool to make that easier to do.

**Pull request closed without merging**
